//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuhrparkmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public int Id { get; set; }
        public string Zweck { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Ende { get; set; }
        public int Kilometerplan { get; set; }
        public int MitarbeiterId { get; set; }
        public Nullable<int> FahrzeugId { get; set; }
    
        public virtual Mitarbeiter AngelegtVon { get; set; }
        public virtual Fahrzeug MitFahrzeug { get; set; }
    }
}
