//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuhrparkmanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fahrzeug()
        {
            this.InBuchungEnthalten = new HashSet<Buchung>();
        }
    
        public int Id { get; set; }
        public string Kennzeichen { get; set; }
        public string Farbe { get; set; }
        public int Kilometerstand { get; set; }
        public int FahrzeugtypId { get; set; }
    
        public virtual Fahrzeugtyp IstVomTyp { get; set; }
        public virtual Mitarbeiter Hauptnutzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> InBuchungEnthalten { get; set; }
    }
}
